[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
    "npm ci",
    "npm rebuild @swc/core"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "1337"
