[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
    "mkdir -p public/uploads",
    "mkdir -p data",
    "npm install",
    "rm -rf node_modules/sharp",
    "npm install --os=linux --cpu=x64 sharp"
]

[phases.build]
cmds = [
    "NODE_ENV=production npm run build"
]

[start]
cmd = "NODE_ENV=production npm start"

[variables]
NODE_ENV = "production"
PORT = "1337"
STRAPI_DISABLE_REMOTE_DATA_TRANSFER = "true"
